#!/bin/bash

# bash_exports

# Disable Autocorrect typos in path names when using `cd`
shopt -u cdspell

# Check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Disable Case-insensitive globbing (used in pathname expansion)
shopt -u nocaseglob
