#!/bin/bash

run_brew() {

    # Check for Homebrew
    if type_exists 'brew'; then
        e_header "Updating Homebrew..."
        # Use the latest version of Homebrew
        brew update --all
        [[ $? ]] && e_success "Done"

        e_header "Updating any existing Homebrew formulae..."
        # Upgrade any already-installed formulae
        brew upgrade --all
        [[ $? ]] && e_success "Done"

        e_header "Checking status of desired Homebrew formulae..."
        local list_formulae
        local -a missing_formulae
        local -a desired_formulae=(
            'git'
            'ack'
            'bash'
            'bash-completion'
            'node'
            'rsync'
            'wget'
            'heroku-toolbelt'
        )

        for index in ${!desired_formulae[*]}
        do
            if ! formula_exists ${desired_formulae[$index]}; then
                # Store the name (and options) of every missing formula
                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
            fi
        done

        if [[ "$missing_formulae" ]]; then
            # Convert the array of missing formula into a list of space-separate strings
            list_formulae=$( printf "%s " "${missing_formulae[@]}" )

            e_header "Installing missing Homebrew formulae..."
            # Install all missing formulae
            brew install $list_formulae

            [[ $? ]] && e_success "Done"
        fi


        e_header "Installing caskroom/cask/brew-cask..."
        brew tap caskroom/cask
        brew install brew-cask


        e_header "Updating Homebrew Cask..."
        # Use the latest version of Homebrew
        brew cask update --all
        [[ $? ]] && e_success "Done"

        e_header "Updating any existing Homebrew Cask formulae..."
        # Upgrade any already-installed formulae
        brew upgrade --all
        [[ $? ]] && e_success "Done"


        installcask dropbox
        installcask google-chrome
        installcask virtualbox
        installcask vlc
        installcask transmission
        installcask the-unarchiver
        installcask opera
        installcask firefox
        installcask skype
        installcask hipchat
        installcask cleanmymac
        installcask atom
        installcask copy
        installcask charles
        installcask hockey
        installcask spectacle
        installcask iexplorer 
        installcask droplr
        installcask spotify
        installcask flux

        # Remove outdated versions from the Cellar
        brew cleanup
    else
        printf "\n"
        e_error "Error: Homebrew not found."
        printf "Aborting...\n"
        exit
    fi

}

function installcask() {
	if brew cask info "${@}" | grep "Not installed" > /dev/null; then
		brew cask install --appdir=/Applications "${@}"
	else
		echo "${@} is already installed."
	fi
}
