#!/bin/bash

run_help() {

cat <<EOT
OS X dotfiles - Juan Cruz Ghigliani - http://www.juancruzmdq.com.ar

Usage: $(basename "$0") [options]

Options:
    -h, --help      Print this help text
    -l, --list      Print a list of software to be installed
    --no-packages   Suppress package updates
    --no-sync       Suppress pulling from the remote repository

Documentation can be found at https://github.com/juancruzmdq/dotfiles

Copyright (c) Juan Cruz Ghigliani
Licensed under the MIT license.
EOT

}
