#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Juan Cruz Ghigliani - http://juancruzmdq.com.ar/

Additional software installed

With brew
    git
    ack
    bash
    bash-completion
    node
    rsync
    wget
    heroku-toolbelt
    fish
    android-sdk

With brew-cask
    Dropbox
    Google Chrome
    Firefox
    Opera
    VirtualBox
    VLC
    Transmission
    the-unarchiver
    hipchat
    cleanmymac
    atom
    copy
    charles
    hockey
    spectacle
    iexplorer
    droplr
    spotify
    flux
    gimp
    alfred
    dash

EOT

}
