#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Juan Cruz Ghigliani - http://juancruzmdq.com.ar/

Additional software to install

Browsers:
    Firefox
    Google Chrome
    Opera

Development:
    Filezilla
    iTerm 2
    ImageAlpha
    ImageOptim
    VirtualBox
    XAMPP

Other:
    Alfred
    Divvy
    Dropbox
    Flux
    KeePassX
    LimeChat
    Network Connect
    Skype
    uTorrent
    VLC
EOT

}
